GET http://localhost:5000/
Content-Type: application/json

###
GET http://localhost:5000/contact
Content-Type: application/json

###
GET http://localhost:5000/roy123456
Content-Type: application/json

###
POST http://localhost:5000/
Content-Type: application/json

{
    "username": "roy",
    "password": "password123"
}

###
GET http://localhost:5000/api/user
Content-Type: application/json

###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "password123"
}

###
GET http://localhost:5000/api/user/get-users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoibm9ybWFsLXVzZXIiLCJlbWFpbCI6InRlc3Q1QHRlc3QuY29tIiwiaWQiOiI2ODRlODJmYTFiMjI2MWFhYmQ3NzZhNTIiLCJpYXQiOjE3NDk5Nzc3NzcsImV4cCI6MTc1MDA2NDE3N30.z-iVPULRpk61z3ozv4B-UPCXaSsuSlk-yEBK7Gic-fw

###
GET http://localhost:5000/api/user/get-users
Content-Type: application/json

###
GET http://localhost:5000/api/user/user/test@test.com
Content-Type: application/json

###
POST http://localhost:5000/api/user/register-user
Content-Type: application/json

{
    "email": "test5@test.com",
    "password": "password123"
}

###
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoibm9ybWFsLXVzZXIiLCJlbWFpbCI6InRlc3Q0QHRlc3QuY29tIiwiaWQiOiI2ODRlNzU3ZTEwNWM5OTFkNjc0MmY0ZjYiLCJpYXQiOjE3NDk5NzM3MTgsImV4cCI6MTc1MDA2MDExOH0.gKvCYiOu0obDgo05T6aPWqzD_geN_I9yG19sPkadUAs
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email": "test5@test.com",
    "password": "password123"
}

###
POST http://localhost:5000/api/user/delete-user
Content-Type: application/json

{
    "email": "test4@test.com"
}

###
POST http://localhost:5000/api/user/update-user
Content-Type: application/json

{
    "email": "test3@test.com",
    "name": "john doe"
}